sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - openssl aes-256-cbc -K $encrypted_8acaa5b479ff_key -iv $encrypted_8acaa5b479ff_iv -in service-account.json.enc -out service-account.json -d
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project k8s-fib
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials fib-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t kylecooley/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kylecooley/react-test npm run test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
